config/routes.rb
Rails.application.routes.draw do


  devise_for :users


  resources :users, only: [:index, :show]

  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  
  resources :requests, only: [:new, :create, :show, :index]

  resources :stores, only: [:index, :show, :new, :create, :edit, :update]


  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

get 'contact', to: 'messages#new', as: 'contact'
post 'contact', to: 'messages#create'

  get '/' => "requests#new"

  get '/looks' => "looks#home"

end

app/models/message.rb
class Message < ActiveRecord::Base

	
end

app/models/place.rb
class Place < ActiveRecord::Base
end

app/models/request.rb
class Request < ActiveRecord::Base
	belongs_to :user
	validates_presence_of :product, :message => "No dejar campo vacío"
	validates_presence_of :place


	after_create :send_emails


	def has_stores?
	 Store.exists?(place: place)
	end
		
	def send_emails
		store_emails = Store.where(place: place).pluck(:email)

		if user_id?
			requester_name = user.name
			requester_email = user.email
		else
			requester_name = name
			requester_email = email
		end
		store_emails.each do |email|
	 	  RequestMailer.request_email(self, email, requester_name, requester_email).deliver_now
		end
	end

	

end

app/models/store.rb
class Store < ActiveRecord::Base
	geocoded_by :address
	after_validation :geocode

	has_secure_password
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :requests
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  after_initialize :set_default_role, :if => :new_record?

  after_create :welcome_email


private

  def set_default_role
    self.role = :user unless self.role
  end

  def welcome_email
      WelcomeMailer.welcome_email(self).deliver_now
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :current_store

  def admin_only
		unless current_user && current_user.role == "admin"
			flash[:access_denied] = "Acess denied. You must be admin to see this page."
		redirect_to '/'
	end
  end

  	def current_store
  		if @currente_store.nil?
  		@current_store = Store.find_by(id: session[:store_id])
  	end
  	@current_store
  end

  protected
  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

end

app/controllers/looks_controller.rb
class LooksController < ApplicationController
	def home
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

	  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    
    if @message.valid?
      MessageMailer.new_message(@message).deliver
      redirect_to '/contact', :flash => { :success => "Tu mensaje se ha enviado correctamente" } 
    else
      flash[:alert] = "An error occurred while delivering this message."
      render :new
    end
  end

private

  def message_params
    params.require(:message).permit(:name, :email, :content)
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
	before_action :admin_only, only: [:index]

	def new
		@request = Request.new
		@stores = Store.all
		@cities = Place.all
	end

	def create
		@cities = Place.all
	 	request = user_signed_in? ? current_user.requests : Request
	 	@request = request.new request_params
	 	if @request.save
	 		
			flash[:notice] = 'Request created successfully'
			redirect_to request_path(@request.id)
		else 
			render 'new'
		end
		
	end

	def show
		@request = Request.find(params[:id])
		@has_stores = @request.has_stores?
		@stores_by_place = Store.where(place: @request.place)
	end

	def index
	 @requests = Request.all
	end


	private

	def request_params
		params.require(:request).permit(:product, :place, :name, :email)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		store = Store.find_by(email: params[:email])
		if store && store.authenticate(params[:password])
			session[:store_id] = store.id
		redirect_to '/'
	  else
	  	redirect_to 'login'
	  end
	end

	def destroy
		session.clear
		redirect_to '/'
	end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController

	def index
		@stores = Store.all
	end

	def show
		@store = Store.find(params[:id])

 respond_to do |format|
 format.html
 format.json { render json: @store }
 end

	end

	def new
		@store = Store.new
	end

	def create
	 	@store = Store.new store_params
	 	if @store.save
			flash[:info] = 'Tienda almacenada en la base de datos satisfactoriamente'
			redirect_to store_path(@store.id)
		else 
			render 'new'
		end
	end

	def edit
		@store = Store.find(params[:id])
	end

	def update
		@store = Store.find(params[:id])
    if @store.update_attributes(store_params)
    	redirect_to store_path(@store.id)
    else
      render 'edit'
    end
	end

	private

	def store_params
		params.require(:store).permit(:name, :email, :telephone, :place, :postcode, :address, :latitude, :longitude, :apparel, :password, :password_confirmation)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :admin_only, only: [:index]
	before_action :authenticate_user!, only: [:show]

	def index
		@users = User.all
	end
	def show
		@user = User.find(params[:id])
		@requests = @user.requests.all
	end

	 def destroy
    @user = User.find(params[:id])
    @user.destroy

    if @user.destroy
        redirect_to '/', notice: "User deleted."
    end
  end



end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/looks_helper.rb
module LooksHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/looks/home.html.erb
<div class="sup">
  IDEAS DE LOOKS BY LOOKFINDER
</div>
<div class="back">
  <div class="move">
<ul class="photo-grid">
  <li>
      <figure>
        <img src="/look1.jpg" height="500" width="320">
        <figcaption><p>Minifalda de tul negra</p></figcaption>
      </figure>
  </li>
  <li>
      <figure>
        <img src="/look2.jpg" height="500" width="320" >
        <figcaption><p>Falda plisada maxi color rosa</p></figcaption>
      </figure>
  </li>
  <li>
      <figure>
        <img src="/look3.jpg" height="500" width="320">
        <figcaption><p>LBD & Perfecto negra</p></figcaption>
      </figure>
  </li>
</ul>

<ul class="photo-grid">
  <li>
      <figure>
        <img src="/look4.jpg" height="500" width="320">
        <figcaption><p>Velvet body & falda de tul</p></figcaption>
      </figure>
  </li>
  <li>
      <figure>
        <img src="/look5.jpg" height="500" width="320" >
        <figcaption><p>Maxi-Jersey</p></figcaption>
      </figure>
  </li>
  <li>
      <figure>
        <img src="/look8.jpg" height="500" width="320">
        <figcaption><p>Maxi-Chaleco de pelo</p></figcaption>
      </figure>
  </li>
</ul>

<ul class="photo-grid">
  <li>
      <figure>
        <img src="/look10.jpg" height="500" width="320">
        <figcaption><p>Look total White</p></figcaption>
      </figure>
  </li>
  <li>
      <figure>
        <img src="/look11.jpg" height="500" width="320" >
        <figcaption><p>Black jumpsuit & cinturón dorado</p></figcaption>
      </figure>
  </li>
  <li>
      <figure>
        <img src="/look12.jpg" height="500" width="320">
        <figcaption><p>Red Jumpsuit</p></figcaption>
      </figure>
  </li>
</ul>
</div>
</div>

app/views/messages/new.html.erb
<div class="success">
<%= flash[:success] %>
</div>
<div class="container">
<%= form_for @message, url: contact_path do |message_form| %>
  <fieldset>
    <div class="field">
      Nombre<br> <%= message_form.text_field :name, class: 'form_control', placeholder: "Nombre" %><br>
    </div>
    
    <div class="field">
      E-mail<br> <%= message_form.email_field :email, class: 'form_control',  placeholder: "Email"%><br>
    </div>
    
    <div class="field">
     Mensaje<br> <%= message_form.text_area :content, class: 'form_control_area',  placeholder: "Mensaje"%><br>
    </div>
  </fieldset>
  
  <fieldset>
    <div class="field">
      <%= message_form.submit "Enviar", :class => 'btn_send' %>
    </div>
  </fieldset>
<% end %>
</div>

app/views/requests/index.html.erb
<% @requests.each do |request| %>
<ul>
<li>
<%= request.product %>
<%= request.place %>
<%= request.name %>
<%= request.email %>
</li>
</ul>
<% end %>

app/views/requests/new.html.erb
<header>
<article>

<div class="container">

<!-- <div class="welcome">

<div class="row sentence">
	¿Llevas tiempo buscando una falda de tul como la de Carrie Bradshaw? ¿has visto un vestido por la calle y no tienes ni idea de dónde conseguirlo? ¡Ahorra tiempo buscando esa prenda de ropa que tanto deseas! Logeate para guardar tus búsquedas o entra como un usuario anónimo
</div>

</div>
 -->
<div class="row">

<div class="col-md-6">

<div class="form">

<% if user_signed_in? %>


<%= form_for @request do |f| %>

 <strong>¿Qué prenda de ropa o calzado estás buscando?</strong> <br><%= f.text_field :product, class: 'form_control' %> <br><br>


 <strong>¿Dónde? - Selecciona una ciudad del despegable</strong>  <br><%= f.select :place, @cities.map {|c| [c.city] }.sort, {}, {required: 'true', autofocus: 'true', class: 'select_control'} %> <br><br>

  <%= f.submit "LOOKFIND", :class => 'btn_lookFinder' %>

<% end %>
<% else %>

<%= form_for @request do |f| %>

 <strong>¿Qué prenda de ropa o calzado estás buscando?</strong> <br><%= f.text_field :product, :placeholder => " Pantalones palazzo color negro", class: 'form_control' %><br><br>

 <strong>¿Dónde? Selecciona una ciudad del desplegable</strong>  <br> <%= f.select :place, @cities.map {|c| [c.city] }.sort, {}, {required: 'true', autofocus: 'true',  class: 'select_control'} %><br><br>


  <strong>Déjanos tu nombre</strong> <br><%= f.text_field :name, :placeholder => " Escribe tu nombre aquí",class: 'form_control' %><br><br>
 
  <strong>Y por último tu e-mail</strong> <br><%= f.email_field :email, :placeholder => " lookfinder@lookfinder.com", class: 'form_control' %><br><br>


  <%= f.submit "LOOKFIND", :class => 'btn_lookFinder' %>

<% end %>
<% end %>

<% if @request.errors.any? %>
<% @request.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
<% end %>
<% end %>
</div>

</div>

</div>

</article>

  <p> EL PUNTO DE ENCUENTRO CON LAS TIENDAS DE TU CIUDAD </p>

</header>
<main>
	
	<div class="row explication">
		<div class="col-md-4 description">
		<div class="titles">USUARIOS</div>
	  Escribe lo que estás buscando: una falda de tul, una americana de terciopelo, un top de paillettes... Especfica el producto al máximo con color o talla, o haz una búsqueda más amplia. Haz la búsqueda registrad@ o sin registrar, lo que tu prefieras, elige en qué ciudad estás buscando el producto y espera a que la tiendas que tienen el producto contacten contigo por e-mail.
	</div>
		<div class="col-md-4 description">
		<div class="titles">TIENDAS</div>
	  Forma parte de la base de datos de LookFinder y aumenta las visitas a tu tienda. Recibirás al instante y en tu cuenta de correo electrónico las búsquedas de los usuarios que están tratando de encontrar una prenda en tu ciudad. Si tienes la prenda buscada respóndeles y consigue fácilmente un posible nuevo cliente. 
	</div>
	<div class="col-md-4 description">
		<div class="titles">LOOKFINDER</div>
	 Utiliza Lookfinder y ahorra tiempo y esfuerzos. Se acabó recorrer toda la ciudad buscando un cinturón joya o un LBD, se acabó navegar por Internet horas y horas y esperar a que te traigan a casa lo comprado para saber si es exactamente lo que estabas buscando. LOOKFINDER: pone en contacto usuarios y tiendas de una misma ciudad. 
	</div>
	 </div>
</main>

app/views/requests/show.html.erb
<div class="show">

<% if @has_stores %>


<div class="responseto">
¡Hola <strong><%= @request.name %></strong>! ¡Gracias por utilizar LookFinder!
Las tiendas de <%= @request.place %> han recibido lo que buscas. Si lo tienen se pondrán en contacto contigo. Puedes echar un vistazo a nuestras ideas de <%= link_to 'looks', looks_path %> para buscar tus próximas prendas, o ver a continuación las <strong>tiendas de tu área</strong> de nuestra base de datos. Puedes ponerte en contacto con ellas y preguntarles directamente:

</div>

<div class="row">
<% @stores_by_place.each do |store| %>
<div class="col-md-4 backprofile">
<ul>
<li class="storebox">
<strong><%= store.name %></strong><br>
<%= store.email %><br>
<%= store.telephone %><br>
<%= image_tag "http://maps.google.com/maps/api/staticmap?size=300x150&sensor=false&zoom=14&markers=#{store.latitude}%2C#{store.longitude}" %><br>
<%= link_to 'Ver más', store_path(store) %>
</li>
</ul>
</div>
<% end %>


</div>

<% else %>
<div class="are">
Hola <%= @request.name %> En este momento no hay tiendas de <%= @request.place %> en nuestra base de datos pero pasa pronto de nuevo por LookFinder porque seguro que ya hemos incorporado nuevas tiendas.
Gracias!
</div>

<% end %>

</div>

app/views/stores/edit.html.erb
<div class="edit">
<h3>Actualiza tu perfil de tienda</h3>

<div class="row">
<%= form_for @store do |f| %>

<div class="col-md-6">

Nombre del comercio: <br><%= f.text_field :name, class: 'form_control' %><br>

Email: <br><%= f.email_field :email, class: 'form_control' %><br>

Teléfono <br> <%= f.text_field :telephone, class: 'form_control' %><br>

Ciudad<br><%= f.text_field :place, class: 'form_control' %><br>

<strong>Código postal</strong><br><%= f.text_field :postcode, class: 'form_control' %><br>

<strong>Dirección</strong><br><%= f.text_field :address, class: 'form_control' %><br>

</div>

<div class="col-md-6">

<strong>Descripción de productos</strong><br><%= f.text_area :apparel, class: 'form_control_area' %><br>

<strong>Latitud</strong><br><%= f.number_field :latitude, :step => 'any', class: 'form_control'%><br>

<strong>Longitud</strong><br><%= f.number_field :longitude, :step => 'any', class: 'form_control' %><br>

<strong>Password</strong><br> <%= f.password_field :password, class: 'form_control' %><br>
<strong>Confirmar password</strong><br> <%= f.password_field :password_confirmation, class: 'form_control' %>
 
 <br>
 
<br>

  <%= f.submit "Save", :class => 'btn_Save' %>

<% end %>
</div>
</div>
</div>

app/views/stores/home.html.erb
<div class="log_stores">

<%= link_to "Log in", "/login" %><br>
<%= link_to "Log out", "/logout", :method => :delete %>

</div>

app/views/stores/index.html.erb
<div class="stores-list">
<ul>
<% @stores.each do |store| %>
<li class="store-list">
<strong><%= store.name %></strong>
<%= store.place %>
<%= store.email %>
<%= store.telephone %>
<%= store.address %>
<%= link_to 'Ver más', store_path(store) %>
</li>
<br>
<% end %>
</ul>
</div>

app/views/stores/new.html.erb
<div class="container">
Estás a un paso de formar parte de la base de datos de tiendas de LOOKFINDER. Una vez hayas completado este formulario comenzarás a recibir las peticiones de los usuarios de tu zona.
<div class="row">
<%= form_for @store do |f| %>

<div class="col-md-6">

<srong>Nombre de la tienda:</strong><br><%= f.text_field :name, class: 'form_control' %><br>

<strong>Email:</strong><br><%= f.email_field :email, class: 'form_control' %><br>

<strong>Teléfono</strong><br> <%= f.text_field :telephone, class: 'form_control' %><br>

<strong>Ciudad</strong><br><%= f.text_field :place, class: 'form_control' %><br>

<strong>Código postal</strong><br><%= f.text_field :postcode, class: 'form_control' %><br>

<strong>Dirección</strong><br><%= f.text_field :address, class: 'form_control' %><br>

</div>

<div class="col-md-6">

<strong>Descripción de productos y/o marcas</strong><br><%= f.text_area :apparel, class: 'form_control_area' %><br>

<!-- <strong>Latitud</strong><br><%= f.number_field :latitude, :step => 'any', class: 'form_control'%><br>

<strong>Longitud</strong><br><%= f.number_field :longitude, :step => 'any', class: 'form_control' %><br> -->

<strong>Contraseña</strong><br> <%= f.password_field :password, class: 'form_control' %><br>
<strong>Confirmar contraseña</strong><br> <%= f.password_field :password_confirmation, class: 'form_control' %>
 
 <br>
 
<br>

  <%= f.submit "Save", :class => 'btn_Save' %>

<% end %>
</div>
</div>
</div>

app/views/stores/show.html.erb
<div class="notice">
<%= flash[:info] %>
</div>

<div class="row profile">

<div class="col-md-6 info">
<h3><%= @store.name %></h3>

<%= @store.place %><br>
<%= @store.address %><br>
<%= @store.postcode %><br>
<%= @store.telephone %><br>
<%= @store.apparel %><br>


</div>

<div class="col-md-6">

<div id="places">
<div id="map"></div>
</div>

</div>

</div>

  

  

app/views/users/index.html.erb
<% @users.each do |user| %>
<%= user.name %>
<% end %>

app/views/users/show.html.erb
<div class="show-profile">

Hola <strong><%= @user.name %></strong> <br>

Éste tu historial de búsquedas realizadas en LOOKFINDER:
<div class="row boxes">
<ul>
 <% @requests.each do |request| %>
 <div class="col-md-4">
<li class="boxes">
 Producto: <strong><%= request.product %></strong><br>
 Ciudad: <%= request.place %> <br>
 Búsqueda realizada el: <%= request.created_at.strftime('%d/%m/%Y') %> <br>
 <br>
</li>
</div>
  <% end %>

</ul>

</div>

<%= link_to "Darme de baja de LookFinder", admin_destroy_user_path(@user), method: :delete, data: { confirm: "¿Estás seguro de que deseas darte de baja de LookFinder?" } %>

</div>