config/routes.rb
Rails.application.routes.draw do


  devise_for :users


  resources :users, only: [:index, :show]

  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  
  resources :requests, only: [:new, :create, :show, :index]

  resources :stores, only: [:index, :show, :new, :create, :edit, :update]


  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

get 'contact', to: 'messages#new', as: 'contact'
post 'contact', to: 'messages#create'

  get '/' => "requests#new"

  get '/looks' => "looks#home"

end

app/models/message.rb
class Message < ActiveRecord::Base

	
end

app/models/place.rb
class Place < ActiveRecord::Base
end

app/models/request.rb
class Request < ActiveRecord::Base
	belongs_to :user
	validates_presence_of :product, :message => "No dejar campo vacío"
	validates_presence_of :place


	after_create :send_emails


	def has_stores?
	 Store.exists?(place: place)
	end
		
	def send_emails
		store_emails = Store.where(place: place).pluck(:email)

		if user_id?
			requester_name = user.name
			requester_email = user.email
		else
			requester_name = name
			requester_email = email
		end
		store_emails.each do |email|
	 	  RequestMailer.request_email(self, email, requester_name, requester_email).deliver_now
		end
	end

	

end

app/models/store.rb
class Store < ActiveRecord::Base
	geocoded_by :address
	after_validation :geocode

	has_secure_password
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :requests
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  after_initialize :set_default_role, :if => :new_record?

  after_create :welcome_email


private

  def set_default_role
    self.role = :user unless self.role
  end

  def welcome_email
      WelcomeMailer.welcome_email(self).deliver_now
  end


end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

end

app/controllers/looks_controller.rb
class LooksController < ApplicationController
	def home
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

	  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    
    if @message.valid?
      MessageMailer.new_message(@message).deliver
      redirect_to '/contact', :flash => { :success => "Tu mensaje se ha enviado correctamente" } 
    else
      flash[:alert] = "An error occurred while delivering this message."
      render :new
    end
  end

private

  def message_params
    params.require(:message).permit(:name, :email, :content)
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
	before_action :admin_only, only: [:index]

	def new
		@request = Request.new
		@stores = Store.all
		@cities = Place.all
	end

	def create
		@cities = Place.all
	 	request = user_signed_in? ? current_user.requests : Request
	 	@request = request.new request_params
	 	if @request.save
	 		
			flash[:notice] = 'Request created successfully'
			redirect_to request_path(@request.id)
		else 
			render 'new'
		end
		
	end

	def show
		@request = Request.find(params[:id])
		@has_stores = @request.has_stores?
		@stores_by_place = Store.where(place: @request.place)
	end

	def index
	 @requests = Request.all
	end


	private

	def request_params
		params.require(:request).permit(:product, :place, :name, :email)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		store = Store.find_by(email: params[:email])
		if store && store.authenticate(params[:password])
			session[:store_id] = store.id
		redirect_to '/'
	  else
	  	redirect_to 'login'
	  end
	end

	def destroy
		session.clear
		redirect_to '/'
	end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController

	def index
		@stores = Store.all
	end

	def show
		@store = Store.find(params[:id])

 respond_to do |format|
 format.html
 format.json { render json: @store }
 end

	end

	def new
		@store = Store.new
	end

	def create
	 	@store = Store.new store_params
	 	if @store.save
			flash[:info] = 'Tienda almacenada en la base de datos satisfactoriamente'
			redirect_to store_path(@store.id)
		else 
			render 'new'
		end
	end

	def edit
		@store = Store.find(params[:id])
	end

	def update
		@store = Store.find(params[:id])
    if @store.update_attributes(store_params)
    	redirect_to store_path(@store.id)
    else
      render 'edit'
    end
	end

	private

	def store_params
		params.require(:store).permit(:name, :email, :telephone, :place, :postcode, :address, :latitude, :longitude, :apparel, :password, :password_confirmation)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :admin_only, only: [:index]
	before_action :authenticate_user!, only: [:show]

	def index
		@users = User.all
	end
	def show
		@user = User.find(params[:id])
		@requests = @user.requests.all
	end

	 def destroy
    @user = User.find(params[:id])
    @user.destroy

    if @user.destroy
        redirect_to '/', notice: "User deleted."
    end
  end



end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/looks_helper.rb
module LooksHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lookfinder</title>
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
   <!-- <link rel="stylesheet" type="text/css" href="index.css"> -->
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?libraries=places"></script>
  <%= javascript_include_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <link href='https://fonts.googleapis.com/css?family=Poiret+One|Josefin+Sans' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

<body>
	
<div id="wraper">

<div id="header">

	<div class="col-sm-4">
		<div class='logo'><%= link_to image_tag("/LOGO.png", :height => 100, :width => 350), '/' %></div>
	</div>
	
	<div class="col-sm-8 nav">
	<ul>
	<h5>
	<li><%= link_to 'LookFinder', '/' %></li>
	<li><%= link_to 'Looks', '/looks' %></li>
	<% if user_signed_in? %>
		
		<li><%= link_to 'Nueva búsqueda', '/' %></li>
		<li><%= link_to 'Perfil', user_path(current_user) %></li>
		<li><%= link_to 'Salir', destroy_user_session_path, method: 'DELETE' %></li>
		<li class="loged">Bienvenido <%= current_user.name %></li>

		<% else %>
		<li><%= link_to 'Registro', new_user_registration_path %></li>
		<li><%= link_to 'Entrar', new_user_session_path %></li>
		<% end %>
	</h5>
	</ul>
   </div>

</div>

<div id="content">

<%= yield %>

</div>

<div id="footer">
	<ul>
		<li><%= link_to 'Contacta con LookFinder', '/contact' %></li>
	</ul>
	<ul>
		¿Eres una tienda? Date de alta en nuestra base de datos y forma parte de LOOKFINDER <%= link_to 'Registrarse', new_store_path %> <br>
	</ul>
	<ul>
		¿Ya formas parte de la base de datos? Accede a tu perfil de tienda <%= link_to 'Acceder', '/login' %><br>
	</ul>
	<ul>
<% if current_store %>
Estás conectado a tu perfil de tienda:<br>
<%= link_to "Actualiza tu perfil", edit_store_path(current_store) %><br>
<%= link_to "Log out", "/logout", :method => :delete %>
<% end %>
	</ul>
</div>

</div>

</body>

</html>